# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
