# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='Enter Location', max_length=50),
        ),
    ]
