# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190706_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='No description has been given'),
        ),
    ]
