# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood_id',
            new_name='neighbourhood',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Enter Location', max_length=30),
        ),
    ]
